#!/usr/bin/env python3
"""
AutoBricks AI MCP exec-bridge — exposes a small Model Context Protocol server
on the bot so a remote coding agent (Claude Code, Cursor, Zed, …) can take
shell + file actions on the bot from the user's local machine.

Architecture
------------
- Runs as the workspace user (UID 1000) under supervisord.
- Binds 127.0.0.1:9876 — Traefik routes ``https://<bot>/__mcp/*`` to it.
- Auth: bearer token in ``Authorization: Bearer <ABAI_MCP_TOKEN>``. The
  token is generated by autobricks at provision time and written to
  /opt/data/.env; the bot owner rotates it from the UI.
- Implements the MCP "streamable HTTP" transport per the spec
  (https://modelcontextprotocol.io/specification/2025-06-18/basic/transports/)
  so any MCP-aware client can connect with one ``claude mcp add`` line.

Tools exposed
-------------
- run_command(cmd, cwd?, timeout?) → {stdout, stderr, exit_code}
- read_file(path) → {content}
- write_file(path, content) → {bytes_written}

The file ops are bounded to /opt/data and /opt/hermes/skills — the agent
can't accidentally read /etc/shadow or write to /usr/bin. Sudo wrapping is
the user's responsibility (e.g. they prompt Claude to "use sudo to install
…"), and only works on Kata bots per the entrypoint gate.
"""
from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import time
import uuid
from pathlib import Path
from typing import Any

from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse, Response

# ─── Config ──────────────────────────────────────────────────────────────────

LOG = logging.getLogger("abai-mcp")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")

# Token is read at request time (not startup) so rotations take effect
# without restarting this process — the autobricks rotate-token endpoint
# rewrites .env and ``supervisorctl reload`` is enough.
TOKEN_PATH = "/opt/data/.env"
TOKEN_KEY = "ABAI_MCP_TOKEN"

# Allowed roots for file ops. Tightening this is the only knob the user gets
# for sandboxing; everything else they want they can do via run_command.
FILE_ROOTS = (
    Path("/opt/data"),
    Path("/opt/hermes/skills"),
)

# Hard cap to keep a runaway command from filling memory.
RUN_TIMEOUT_DEFAULT = 60
RUN_TIMEOUT_MAX = 600
RUN_OUTPUT_MAX = 200_000  # 200 KB per stream

# ─── App ─────────────────────────────────────────────────────────────────────

app = FastAPI(title="abai-mcp", docs_url=None, redoc_url=None, openapi_url=None)


def _read_token() -> str:
    """Read ABAI_MCP_TOKEN from /opt/data/.env each request — supports
    rotation without process restart."""
    try:
        with open(TOKEN_PATH, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, _, v = line.partition("=")
                if k.strip() == TOKEN_KEY:
                    return v.strip().strip('"').strip("'")
    except FileNotFoundError:
        return ""
    return ""


def _check_auth(authorization: str | None) -> None:
    """Reject anything that isn't a valid Bearer matching the live token."""
    expected = _read_token()
    if not expected:
        raise HTTPException(503, "ABAI_MCP_TOKEN not set on this bot")
    if not authorization or not authorization.lower().startswith("bearer "):
        raise HTTPException(401, "missing Authorization: Bearer …")
    presented = authorization.split(None, 1)[1].strip()
    # Constant-time compare to avoid leaking via timing.
    import hmac
    if not hmac.compare_digest(presented, expected):
        raise HTTPException(401, "invalid token")


def _validate_path(path: str) -> Path:
    """Resolve path and ensure it's under one of FILE_ROOTS. Raises HTTPException
    400 otherwise. Returns the resolved path."""
    if not isinstance(path, str) or not path:
        raise HTTPException(400, "path must be a non-empty string")
    p = Path(path).resolve()
    for root in FILE_ROOTS:
        try:
            p.relative_to(root.resolve())
            return p
        except ValueError:
            continue
    raise HTTPException(
        400,
        f"path must be inside one of: {', '.join(str(r) for r in FILE_ROOTS)}",
    )


# ─── Tool implementations ────────────────────────────────────────────────────


def _tool_run_command(args: dict[str, Any]) -> dict[str, Any]:
    cmd = args.get("cmd")
    cwd = args.get("cwd")
    timeout = args.get("timeout", RUN_TIMEOUT_DEFAULT)
    if not isinstance(cmd, str) or not cmd.strip():
        raise HTTPException(400, "cmd must be a non-empty string")
    if cwd is not None and not isinstance(cwd, str):
        raise HTTPException(400, "cwd must be a string if provided")
    if not isinstance(timeout, (int, float)) or timeout <= 0:
        raise HTTPException(400, "timeout must be a positive number")
    timeout = min(int(timeout), RUN_TIMEOUT_MAX)
    started = time.monotonic()
    try:
        proc = subprocess.run(
            ["/bin/bash", "-lc", cmd],
            cwd=cwd or "/opt/data",
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        stdout = proc.stdout[:RUN_OUTPUT_MAX]
        stderr = proc.stderr[:RUN_OUTPUT_MAX]
        if len(proc.stdout) > RUN_OUTPUT_MAX:
            stdout += f"\n[truncated, {len(proc.stdout) - RUN_OUTPUT_MAX} bytes elided]"
        if len(proc.stderr) > RUN_OUTPUT_MAX:
            stderr += f"\n[truncated, {len(proc.stderr) - RUN_OUTPUT_MAX} bytes elided]"
        return {
            "stdout": stdout,
            "stderr": stderr,
            "exit_code": proc.returncode,
            "duration_s": round(time.monotonic() - started, 3),
        }
    except subprocess.TimeoutExpired as e:
        return {
            "stdout": (e.stdout or b"").decode("utf-8", "replace")[:RUN_OUTPUT_MAX],
            "stderr": (e.stderr or b"").decode("utf-8", "replace")[:RUN_OUTPUT_MAX],
            "exit_code": -1,
            "duration_s": round(time.monotonic() - started, 3),
            "timed_out": True,
        }


def _tool_read_file(args: dict[str, Any]) -> dict[str, Any]:
    p = _validate_path(args.get("path", ""))
    try:
        return {"content": p.read_text(encoding="utf-8"), "path": str(p)}
    except FileNotFoundError:
        raise HTTPException(404, f"not found: {p}")
    except UnicodeDecodeError:
        raise HTTPException(415, "file is not utf-8; try run_command(\"base64 …\")")


def _tool_write_file(args: dict[str, Any]) -> dict[str, Any]:
    p = _validate_path(args.get("path", ""))
    content = args.get("content")
    if not isinstance(content, str):
        raise HTTPException(400, "content must be a string")
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return {"path": str(p), "bytes_written": len(content.encode("utf-8"))}


TOOL_DEFS = [
    {
        "name": "run_command",
        "description": (
            "Run a shell command on the bot as the workspace user. Sudo "
            "available on Kata bots only. Returns stdout, stderr, exit_code, "
            "duration_s. Use this for apt-get install, supervisorctl, git, "
            "etc."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "cmd": {"type": "string", "description": "Command to run via /bin/bash -lc"},
                "cwd": {"type": "string", "description": "Working dir (default /opt/data)"},
                "timeout": {"type": "number", "description": f"Seconds, default {RUN_TIMEOUT_DEFAULT}, max {RUN_TIMEOUT_MAX}"},
            },
            "required": ["cmd"],
        },
    },
    {
        "name": "read_file",
        "description": (
            "Read a UTF-8 text file from /opt/data or /opt/hermes/skills. "
            "For binary files, use run_command(\"base64 <path>\")."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
        },
    },
    {
        "name": "write_file",
        "description": (
            "Write a UTF-8 file under /opt/data or /opt/hermes/skills. "
            "Creates parent dirs if needed. Returns bytes written."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "content": {"type": "string"},
            },
            "required": ["path", "content"],
        },
    },
]

TOOL_HANDLERS = {
    "run_command": _tool_run_command,
    "read_file": _tool_read_file,
    "write_file": _tool_write_file,
}


# ─── MCP JSON-RPC over Streamable HTTP ────────────────────────────────────────

SERVER_INFO = {
    "name": "abai-mcp",
    "version": "1.0.0",
}

PROTOCOL_VERSION = "2025-06-18"


def _rpc_error(req_id: Any, code: int, message: str) -> dict[str, Any]:
    return {"jsonrpc": "2.0", "id": req_id, "error": {"code": code, "message": message}}


def _rpc_result(req_id: Any, result: Any) -> dict[str, Any]:
    return {"jsonrpc": "2.0", "id": req_id, "result": result}


def _handle_rpc(msg: dict[str, Any]) -> dict[str, Any] | None:
    """Dispatch one JSON-RPC request, return the response dict (or None for
    notifications, which get no reply)."""
    method = msg.get("method")
    params = msg.get("params") or {}
    req_id = msg.get("id")
    is_notification = req_id is None

    if method == "initialize":
        return _rpc_result(req_id, {
            "protocolVersion": PROTOCOL_VERSION,
            "capabilities": {"tools": {"listChanged": False}},
            "serverInfo": SERVER_INFO,
        })
    if method == "notifications/initialized":
        # Notification — no response.
        return None
    if method == "tools/list":
        return _rpc_result(req_id, {"tools": TOOL_DEFS})
    if method == "tools/call":
        name = params.get("name")
        args = params.get("arguments") or {}
        handler = TOOL_HANDLERS.get(name)
        if not handler:
            return _rpc_error(req_id, -32601, f"unknown tool: {name}")
        try:
            out = handler(args)
        except HTTPException as exc:
            return _rpc_result(req_id, {
                "isError": True,
                "content": [{"type": "text", "text": f"{exc.status_code} {exc.detail}"}],
            })
        except Exception as exc:
            LOG.exception("tool %s raised", name)
            return _rpc_result(req_id, {
                "isError": True,
                "content": [{"type": "text", "text": f"internal error: {exc}"}],
            })
        return _rpc_result(req_id, {
            "content": [{"type": "text", "text": json.dumps(out, ensure_ascii=False)}],
            "structuredContent": out,
            "isError": False,
        })
    if method == "ping":
        return _rpc_result(req_id, {})
    if is_notification:
        return None
    return _rpc_error(req_id, -32601, f"method not found: {method}")


@app.get("/healthz")
async def healthz():
    return {"ok": True}


@app.post("/mcp")
async def mcp_post(request: Request, authorization: str | None = Header(default=None)):
    """Single-shot JSON-RPC over HTTP. Each request POSTs one message and
    receives one response (or 204 for notifications). This is the "streamable
    HTTP" transport described by the MCP spec, in its simplest form — no SSE
    needed for short tool calls."""
    _check_auth(authorization)
    try:
        msg = await request.json()
    except Exception:
        raise HTTPException(400, "body must be JSON")
    if not isinstance(msg, dict):
        raise HTTPException(400, "body must be a JSON-RPC object")
    resp = _handle_rpc(msg)
    if resp is None:
        return Response(status_code=204)
    return JSONResponse(resp)


@app.get("/mcp")
async def mcp_get(authorization: str | None = Header(default=None)):
    """Some clients call GET /mcp first to check liveness. We don't open an
    SSE stream from the server side — auth is checked and 200 returned so the
    client can proceed to POST messages."""
    _check_auth(authorization)
    return JSONResponse({"ok": True, "transport": "streamable-http"})


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("ABAI_MCP_PORT", "9876"))
    # Bind 0.0.0.0 so Traefik (in a different network namespace) can reach
    # the bot container's IP:9876. Loopback would only be reachable from
    # inside the same netns, which produced a fleet-wide /__mcp 502.
    # Token auth (ABAI_MCP_TOKEN) still gates every route, and only port
    # 9876 is forwarded by Traefik with the /__mcp PathPrefix label.
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
